include:
  - board: nice_nano_v2
    shield: sofle_custom_left
  - board: nice_nano_v2
    shield: sofle_custom_right

artifacts:
  - build/zephyr/nice_nano_v2-sofle_custom_left/.config
  - build/zephyr/nice_nano_v2-sofle_custom_right/.config
