CONFIG_ZMK_KEYBOARD_NAME="Cantanker"
CONFIG_ZMK_KEYBOARD_SCAN=y
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_POINTING=y
# Change the deep sleep timeout (ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_INPUT=y
CONFIG_I2C=y